### PR TITLE
Update to CLDR 32.0.1

### PR DESCRIPTION
**Pull request by nijel**
I've also switched to using 'en' language instead of 'en-US' as the latter seems to be no longer present (there is 'en-US-POSIX').

### CODE REVIEW

**Comment by mlocati** [comment]
Thanks! Did you build the json yourself?

**Comment by nijel** [comment]
No, I've used https://github.com/unicode-cldr/cldr-json

I was thinking about adding those as submodules to make updates easier, but I wanted to make the changes as simple as possible so I've rather copied the needed files. In case you're interested in this, I can submit another PR.

**Comment by mlocati** [comment]
> No, I've used https://github.com/unicode-cldr/cldr-json

I've seen in the past many errors in that repository, so I'm reluctant in merging this PR.
I usually build the JSON data myself starting from the CLDR XML data.
BTW version 32.0.1 can't be build at the moment because of an error (see https://unicode.org/cldr/trac/ticket/10860 ).

**Comment by nijel** [comment]
Ah I was not aware of this. Anyway the diff looked okay to me (few added names and plurals).

**Comment by mlocati** [comment]
I just updated the data to CLDR 33.1. Thanks anyway!

**Pull request closed without merging**
