### PR TITLE
Add a shebang to bin/export.php.

### PR DESCRIPTION
**Pull request by bowlofeggs**
Signed-off-by: Randy Barlow <randy@electronsweatshop.com>

### CODE REVIEW

**Comment by mlocati** [comment]
Wouldn't this output that line on Windows?

**Comment by bowlofeggs** [comment]
@mlocati I don't know PHP particularly well and I don't have a Windows machine to test with, so I can't say for sure. However, I would *expect* the php command line interpreter to ignore the shebang line (as used in your ```bin/export.cmd```. Obviously, don't take my word for it since my knowledge here isn't great.

**Comment by remicollet** [comment]
There are absolutely no problem with the shebang line which is just ignored on Windows.

Can also set execution bit on this file, and drop the uneeded .sh

**Comment by mlocati** [comment]
@remicollet @bowlofeggs What about https://github.com/mlocati/cldr-to-gettext-plural-rules/commit/43e3ffcfa113a882aa839b70287d20b3d08c5edf ?

**Comment by bowlofeggs** [comment]
@mlocati that looks reasonable to me, though I don't think you need to have both the .php file and the extensionless file for Unix systems. As Remi said, you could just put the shebang in the .php file and make it executable and Unix systems will be happy. I don't have a strong preference either way.

**Comment by mlocati** [comment]
I used the same approach as Doctrine. If that commit of mine is OK for you, I'd close this PR and merge that commit

**Comment by bowlofeggs** [comment]
I have no objections.

**Comment by mlocati** [comment]
@bowlofeggs I updated the master branch. If you confirm that the current master suits your needs, I'll add a new release (2.2.0) and close this issue.

**Comment by bowlofeggs** [comment]
Looks fine, thanks!

**Comment by mlocati** [comment]
@bowlofeggs v2.2.0 released

**Comment by bowlofeggs** [comment]
On Mon, 2017-02-06 at 07:25 -0800, Michele Locati wrote:
> @bowlofeggs v2.2.0 released

Thanks!

**Pull request closed without merging**
